name: "ğŸš€ release"

on:
    release:
        types: [published]

jobs:
    release:
        name: "ğŸš€ release"
        runs-on: ubuntu-latest
        steps:
            - name: "ğŸ“š checkout"
              uses: actions/checkout@v2.0.0
            - name: "ğŸŸ¢ node"
              uses: actions/setup-node@v1.4.4
              with:
                  version: 13
                  registry-url: https://registry.npmjs.org/
            - name: "ğŸ“¦ install"
              run: npm install
            - name: "ğŸ§ª test"
              run: npm run test
            - name: "ğŸ‘– coveralls"
              uses: coverallsapp/github-action@v1.1.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: "ğŸš€ publish"
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
